#!/bin/bash

: ${PIZZAINC:="/usr/local/share/pizza"}
PIZZAHOST=$(hostname -f)
PIZZAUSER=$(whoami)
PIZZAART=
PIZZARCV=
PIZZASEND=

help() {
    echo "pizza - sent small ASCII-Icons by Mail"
    echo "--------------------------------------"
    echo "Usage:  -p         Send a pizza (default)"
    echo "        -l         Send a heart"
    echo "        -b         Send happy birthday"
    echo "        -c         Send merry christmas"
    echo "        -m <addr>  Receivers address (non-optional)"
    echo "        -s <addr>  Senders address, defaults to user@host"
    echo "        -h         Print this help-message"
}

if [ ! $1 ]; then
    echo "Argument needed!"
    help
    exit 1
fi

while getopts "plbchm:s:" opt; do
    case ${opt} in
	p )
	    : ${PIZZAART:="pizza"}
	    ;;
	l )
	    : ${PIZZAART:="heart"}
	    ;;
	b )
	    : ${PIZZAART:="birthdaycake"}
	    ;;
	c )
	    : ${PIZZAART:="christmastree"}
	    ;;
	m )
	    PIZZARCV="${OPTARG}"
	    ;;
	s )
	    PIZZASEND="${OPTARG}"
	    ;;
	h )
	    help
	    exit 0
	    ;;
	\?)
	    help
	    exit 1
	    ;;
    esac
done

: ${PIZZAART:="pizza"}
: ${PIZZASEND:="${PIZZAUSER}@${PIZZAHOST}"}

if [ ! $PIZZARCV ]; then
    echo "Argument '-m' and mailaddress needed!"
    help
    exit 1
fi

mail -s "${PIZZAUSER} sent you a ${PIZZAART} on ${PIZZAHOST}!" -S from=${PIZZASEND} ${PIZZARCV} < "${PIZZAINC}/${PIZZAART}"
exit 0
